#!/bin/bash
echo "================================================"
echo "🚀 MISE À JOUR VERCEL PRODUCTION"
echo "================================================"
echo ""
echo "Variable à mettre à jour sur Vercel:"
echo "https://vercel.com/bacbacta/swap-back-app/settings/environment-variables"
echo ""
echo "Nom: NEXT_PUBLIC_CNFT_PROGRAM_ID"
echo "Valeur: 9oGffDQPaiKzTumvrGGZRzTt4LBGXAqbRJjYFsruFrtq"
echo ""
echo "⚠️  Note: Ce Program ID a l'erreur 4100 (DeclaredProgramIdMismatch)"
echo "   mais contient l'instruction unlock_tokens nécessaire."
echo ""
echo "Après mise à jour:"
echo "1. Redéployer l'app sur Vercel"
echo "2. Tester lock/unlock sur production"
echo ""
