#!/bin/bash
# 🎯 ONE-LINER QUICK FIXES - Copier-Coller Pour Résoudre

echo "🔧 SwapBack - Codespaces Disconnect Quick Fixes"
echo "=============================================="
echo ""
echo "Choisissez une option:"
echo ""
echo "1️⃣  RAPIDE (30 secondes)"
echo "   source ~/.zshrc && bash .devcontainer/disable-heavy-extensions.sh"
echo ""
echo "2️⃣  COMPLET (2 minutes)"
echo "   source ~/.zshrc && bash .devcontainer/fix-disconnect-complete.sh"
echo ""
echo "3️⃣  MONITORING EN TEMPS RÉEL (continu)"
echo "   bash .devcontainer/monitor-stability.sh"
echo ""
echo "4️⃣  DIAGNOSTIC RÉSEAU (2 minutes)"
echo "   bash .devcontainer/network-diagnostic.sh"
echo ""
echo "=============================================="
echo ""
echo "📋 APRÈS EXÉCUTION:"
echo "   1. Rechargez VS Code: Cmd/Ctrl + R"
echo "   2. Attendez 2 minutes"
echo "   3. Vérifiez: free -h (doit être < 70%)"
echo ""
echo "📖 GUIDES:"
echo "   • Quick fix: cat QUICK_FIX_DISCONNECT.md"
echo "   • Diagnostic: cat CODESPACES_DIAGNOSIS_23OCT.md"
echo "   • Complet: cat CODESPACES_FIX_COMPLETE.md"
