#!/bin/bash

# Script de build qui gère le problème de Cargo.lock version 4
# Ceci est un workaround temporaire

set -e

echo "🔧 SwapBack Build Script (workaround Cargo.lock v4)"

# Charger l'environnement
source "$HOME/.cargo/env"
export PATH="/home/codespace/.local/share/solana/install/active_release/bin:$PATH"

# Supprimer Cargo.lock s'il existe
if [ -f "Cargo.lock" ]; then
    echo "📝 Suppression de Cargo.lock v4..."
    rm -f Cargo.lock
fi

# Créer un Cargo.lock v3 temporaire
echo "📝 Création d'un Cargo.lock v3 temporaire..."
cat > Cargo.lock << 'EOF'
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 3
EOF

# Installer une version compatible de Rust si nécessaire
RUST_VERSION=$(rustc --version | grep -oP '\d+\.\d+\.\d+' | head -1)
echo "🦀 Version Rust actuelle: $RUST_VERSION"

# Essayer de downgrade vers Rust 1.79 qui utilise Cargo.lock v3
echo "📦 Installation de Rust 1.79 pour compatibilité..."
rustup install 1.79.0 --force-non-host || true
rustup default 1.79.0 || true

# Vérifier la nouvelle version
echo "🦀 Nouvelle version Rust: $(rustc --version)"
echo "📦 Nouvelle version Cargo: $(cargo --version)"

# Nettoyer et rebuild
echo "🧹 Nettoyage..."
rm -rf target
rm -f Cargo.lock

# Build avec anchor
echo "🔨 Build des programmes..."
anchor build

echo "✅ Build terminé!"
echo "📁 Binaires dans: target/deploy/"
ls -lh target/deploy/*.so 2>/dev/null || echo "⚠️  Aucun binaire trouvé"
