#!/bin/bash

echo "🚀 SwapBack - Guide de Test MAINNET"
echo "===================================="
echo ""
echo "📋 Configuration actuelle:"
echo "-------------------------"
echo "Network: $(grep NEXT_PUBLIC_SOLANA_NETWORK app/.env.local | cut -d'=' -f2)"
echo "RPC: $(grep NEXT_PUBLIC_SOLANA_RPC_URL app/.env.local | cut -d'=' -f2)"
echo ""
echo "🎯 Instructions de Test:"
echo "-------------------------"
echo ""
echo "1. ✅ Le serveur Next.js est prêt à démarrer"
echo "   Commande: cd app && npm run dev"
echo ""
echo "2. 🌐 Ouvrir http://localhost:3000"
echo ""
echo "3. 👛 Connecter votre wallet (Phantom/Solflare)"
echo "   ⚠️  IMPORTANT: Assurez-vous d'être sur MAINNET-BETA"
echo "   - Phantom: Settings → Change Network → Mainnet Beta"
echo "   - Solflare: Settings → Network → Mainnet Beta"
echo ""
echo "4. 🔍 Vérifications attendues:"
echo "   ✅ L'indicateur de réseau affiche 'MAINNET' (en vert)"
echo "   ✅ Les routes Jupiter s'affichent pour SOL ↔ USDC"
echo "   ✅ Les prix sont réels (depuis les marchés)"
echo ""
echo "5. 🧪 Test de swap (optionnel):"
echo "   - Input: SOL (0.01 SOL minimum recommandé)"
echo "   - Output: USDC"
echo "   - Cliquer 'Get Quote'"
echo "   - Vérifier que les routes apparaissent"
echo ""
echo "⚠️  ATTENTION:"
echo "   - Sur MAINNET, les swaps coûtent de vrais SOL"
echo "   - Frais de transaction: ~0.000005 SOL (~$0.001)"
echo "   - Commencez par de petits montants pour tester"
echo ""
echo "📊 Si l'affichage montre toujours 'TESTNET':"
echo "   → C'est que votre WALLET est sur testnet/devnet"
echo "   → Changez le réseau du wallet vers Mainnet Beta"
echo "   → L'indicateur se mettra à jour automatiquement"
echo ""
echo "✅ Prêt à tester !"
