name: Build Verification

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build-app:
    name: Build Next.js App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js application
        working-directory: ./app
        run: npm run build

      - name: Check build output
        working-directory: ./app
        run: |
          if [ ! -d ".next" ]; then
            echo "❌ Build failed: .next directory not found"
            exit 1
          fi
          echo "✅ Build successful"

  build-sdk:
    name: Build SDK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build SDK
        working-directory: ./sdk
        run: npm run build

      - name: Check build output
        working-directory: ./sdk
        run: |
          if [ ! -d "dist" ]; then
            echo "❌ SDK build failed: dist directory not found"
            exit 1
          fi
          echo "✅ SDK build successful"
